/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import banco.FornecedorDAO;
import gets_sets.Fornecedor;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author comp8
 */
public class FrameTabelaEstoque extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameTabelaEstoque
     */
    private final String[] columnNames = {"Tipo", "Código", "Fabricante", "Gramatura", "Formato", "Valor", "Máximo em Estoque"};
    private DefaultTableModel model = new DefaultTableModel() {
        private static final long serialVersionUID = 1L;

    };

    public FrameTabelaEstoque() {
        initComponents();
        model.setColumnIdentifiers(columnNames);
        tabelaItens.setModel(model);
        
        
        
        
    }
    
    
    public void attTabela(){
        
        FornecedorDAO fornDAO = new FornecedorDAO();
        List<Fornecedor> lista = fornDAO.getAll();
        
        for(int i=0; i<lista.size(); i++){
            //Fornecedor f = lista.get(i);
            //model.addRow(new Object[]{f.});
            
            //FAZER O DO PAPEL
            
            //"ID", "Tipo", "Código", "Fabricante", "Gramatura", "Formato", "Valor", "Máximo em Estoque"
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaItens = new javax.swing.JTable();

        tabelaItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaItens);
        if (tabelaItens.getColumnModel().getColumnCount() > 0) {
            tabelaItens.getColumnModel().getColumn(0).setResizable(false);
            tabelaItens.getColumnModel().getColumn(1).setResizable(false);
            tabelaItens.getColumnModel().getColumn(2).setResizable(false);
            tabelaItens.getColumnModel().getColumn(3).setResizable(false);
            tabelaItens.getColumnModel().getColumn(4).setResizable(false);
            tabelaItens.getColumnModel().getColumn(5).setResizable(false);
            tabelaItens.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaItens;
    // End of variables declaration//GEN-END:variables
}
