/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import actionListener.Log;
import actionListener.TabelaEstoqueActionListener;
import banco.PapelDAO;
import exception.Exceptions;
import gets_sets.Papel;
import java.awt.Dimension;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author comp8
 */
public class FrameTabelaEstoque extends javax.swing.JInternalFrame {

    private final Log logs = new Log();
    
    /**
     * Creates new form FrameTabelaEstoque
     */
    private TabelaEstoqueActionListener tabelaestoque = new TabelaEstoqueActionListener(this);
    private final String[] columnNames = {"Código", "Tipo", "Fabricante", "Gramatura", "Formato", "Estoque", "Valor"};
    private DefaultTableModel model = new DefaultTableModel() {
        private static final long serialVersionUID = 1L;

    };

    public FrameTabelaEstoque() {
        initComponents();
        model.setColumnIdentifiers(columnNames);
        tabelaItens.setModel(model);
        try {
            attTabela();
        } catch (Exceptions ex) {
            Logger.getLogger(FrameTabelaEstoque.class.getName()).log(Level.SEVERE, null, ex);
            logs.exceptionLog(ex);
        }

        botaoSair.addActionListener(tabelaestoque);

    }

    public int selecionar() {
        int linha = tabelaItens.getSelectedRow();
        if (linha == -1) {
            return -1; //Não tem nada selecionado
        }

        return linha;
    }
    
    public String pegaValor(){
        
        int linha = selecionar();
        String cod_papel = tabelaItens.getValueAt(linha, 0).toString();
        
        return cod_papel;
    }

    public void attTabela() throws Exceptions {

        PapelDAO papelDAO = new PapelDAO();
        List<Papel> lista = papelDAO.getAll();

        for (int i = 0; i < lista.size(); i++) {
            Papel p = lista.get(i);
            model.addRow(new Object[]{p.getTextoCodpapel(), p.getTextoTipopapel(), p.getTextoFormatopapel(), p.getTextoGramaturapapel(), p.getTextoFabricantepapel(), p.getTextoEstoquepapel(), p.getTextoVendaPapel()});

        }
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaItens = new javax.swing.JTable();
        botaoSair = new javax.swing.JButton();

        tabelaItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaItens);
        if (tabelaItens.getColumnModel().getColumnCount() > 0) {
            tabelaItens.getColumnModel().getColumn(0).setResizable(false);
            tabelaItens.getColumnModel().getColumn(1).setResizable(false);
            tabelaItens.getColumnModel().getColumn(2).setResizable(false);
            tabelaItens.getColumnModel().getColumn(3).setResizable(false);
            tabelaItens.getColumnModel().getColumn(4).setResizable(false);
            tabelaItens.getColumnModel().getColumn(5).setResizable(false);
            tabelaItens.getColumnModel().getColumn(6).setResizable(false);
        }

        botaoSair.setText("Sair");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(botaoSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botaoSair)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaItens;
    // End of variables declaration//GEN-END:variables
}
